/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Home_left: typeof import('./src/components/Home_left.vue')['default']
    NavComponent: typeof import('./src/components/NavComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SunMoon: typeof import('./src/components/SunMoon.vue')['default']
  }
}
